pipeline {
    agent any

    environment {
        ROMULUS_ZIP_URL = "https://jenkins.openbmc.org/job/ci-openbmc/lastSuccessfulBuild/distro=ubuntu,label=docker-builder,target=romulus/artifact/openbmc/build/tmp/deploy/images/romulus/*zip*/romulus.zip"
    }

    stages {
        stage('QEMU (OpenBMC эмуляция)') {
            agent { docker { image 'ubuntu:22.04' } }
            steps {
                echo 'Запуск QEMU'
                sh '''
                  apt-get update && apt-get install -y wget unzip expect qemu-system-arm
                  rm -rf romulus romulus.zip || true
                  wget "$ROMULUS_ZIP_URL" -O romulus.zip
                  unzip -o romulus.zip
                  LATEST_MTD=$(ls romulus/obmc-phosphor-image-romulus-*.static.mtd | sort -V | tail -1)

                  expect -c "
                  log_file -a qemu_result.txt
                  spawn qemu-system-arm -m 256 -M romulus-bmc -nographic -drive file=$LATEST_MTD,format=raw,if=mtd -net nic -net user,hostfwd=:0.0.0.0:2222-:22,hostfwd=:0.0.0.0:2443-:443,hostfwd=udp:0.0.0.0:2623-:623,hostname=qemu
                  sleep 30
                  send \\"root\\\\r\\"
                  sleep 4
                  send \\"0penBmc\\\\r\\"
                  expect \\"root@romulus:\\"
                  interact" &
                  echo $! > qemu.pid
                  sleep 60
                '''
            }
        }

        stage('Тесты (lab4, lab5)') {
            agent { docker { image 'python:3.10' } }
            steps {
                echo 'Запуск автотестов и WebUI'
                sh '''
                  pip install --upgrade pip
                  pip install pytest selenium requests

                  cd lab4
                  pytest -v tests.py | tee ../web_results.txt
                  cd ../lab5
                  pytest -v test_redfish.py | tee ../autotest_results.txt
                  cd ..
                '''
                archiveArtifacts artifacts: 'web_results.txt, autotest_results.txt'
            }
        }

        stage('Нагрузочные тесты (lab6)') {
            agent { docker { image 'python:3.10' } }
            steps {
                echo 'Запуск Locust нагрузочных тестов'
                sh '''
                  pip install locust
                  cd lab6
                  timeout 180 locust --headless --users 50 --spawn-rate 5 --run-time 3m --host=https://127.0.0.1:2443 | tee ../locust_results.txt
                  cd ..
                '''
                archiveArtifacts artifacts: 'locust_results.txt'
            }
        }

        stage('Остановка QEMU и очистка') {
            agent { docker { image 'ubuntu:22.04' } }
            steps {
                sh '''
                  echo "Остановить QEMU..."
                  if [ -f "qemu.pid" ]; then
                      QEMU_PID=$(cat qemu.pid)
                      kill $QEMU_PID 2>/dev/null || true
                      rm -f qemu.pid
                  fi
                  rm -rf romulus/ romulus.zip || true
                  rm -f *.log *.pid *.json *.csv *.txt || true
                  du -sh . | awk '{print $1}'
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/*.txt', fingerprint: true
        }
    }
}
